### PR TITLE
A32NX Installation page redesign

### PR DESCRIPTION
**Pull request by saadbruno**
This PR redesigns a bit of the install page to give a better text flow, and improve readability both in desktop and mobile versions of the page.

Things that have changed:

- Aligned text to the left, giving a better text flow over a step by step instruction
- Separated titles from paragraphs (Basically separating "Step #" from the description of the step)
  - This improves creates a hierarchy between title and descriptions
  - This means that the descriptions are not in all-caps anymore, improving readability as well
- Put the warning banner inside a bootstrap alert, so it looks nicer
- Made all columns a `col-lg-8` for consistency
- Made it clear that the installer and manual installations are 2 separate ways of achieving the same thing, by putting them inside `Option 1` and `Option 2` titles.
- Grouped all steps in a single `row` bootstrap element, separating each step by a `col`, which means there are less divs overall

# Desktop
## Before
image

## After
image

# Mobile
## Before
image

## After
image

### CODE REVIEW

**Comment by Benjozork** [comment]
I like this.

**Comment by hafijavid** [comment]
This is good. Just one question (unrelated to your changes), how do you preview your changes?

**Comment by saadbruno** [comment]
You need node installed

Then clone the repo and `cd` into it
Run `npm install`
Run `npm run start`

It should open your browser at localhost:4000 (or 3000, can't remember now)

**Comment by Benjozork** [comment]
LGTM

**Pull request merged**
