### PR TITLE
Added Ground School Page Content

### PR DESCRIPTION
**Pull request by professoralex13**
Added Content to Ground School Page with similar styling to Home Page
image
Photo is From Latest Commit(Changed Colours)

### CODE REVIEW

**Comment by NathanInnes** [comment]
Think overall design could be improved but great start.

**Comment by professoralex13** [comment]
> Think overall design could be improved but great start.

Do you have any Suggestions on how to improve it?

**Comment by NathanInnes** [comment]
We could have a sit down chat in discord about it, very hard through text to explain what can be improved. Think a brain storming session would help

**Comment by HOURLAY270** [comment]
Congratulations about your collaboration into "flybywire".
I am retired from commercial aviation. I have been Avionics Technician & our OS is based on "ARINC", ref. to: "www.collins.com". I like your "aviation training program", I have been avionics teacher part-time for my Company, perhaps may I join your community...I have to  understand how to join you efficiently. Thank you for having contacted me.
Happy New Year
________________________________
De : Nathan Innes <notifications@github.com>
Envoyé : samedi 26 décembre 2020 01:36
À : flybywiresim/flybywiresim-website <flybywiresim-website@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [flybywiresim/flybywiresim-website] Added Ground School Page Content (#22)


Merged #22<https://github.com/flybywiresim/flybywiresim-website/pull/22> into sabes.

**Pull request merged**
